### ISSUE TITLE
map-monitor.sh does nothing

### ISSUE THREAD

**Issue by danielgrom** [kyledayton/HuionKamvasGT220v2LinuxDriver#2]
I have a 220 pro and another monitor, I edited the file, started the driver then the map-monitor, and my tablet maps the screen of the two monitors. Here is the file, is something wrong?

#!/bin/bash
# Edit these to match your setup:

XSCREEN_WIDTH=1920
XSCREEN_HEIGHT=1080

TABLET_WIDTH=1920
TABLET_HEIGHT=1080

TABLET_OFFSET_X=0
TABLET_OFFSET_Y=0

############## Don't Edit this! ##############
C0=`echo "scale=8;$TABLET_WIDTH / $XSCREEN_WIDTH" | bc`
C1=`echo "scale=8;$TABLET_OFFSET_X/$XSCREEN_WIDTH" | bc`
C2=`echo "scale=8;$TABLET_HEIGHT/$XSCREEN_HEIGHT" | bc`
C3=`echo "scale=8;$TABLET_OFFSET_Y/$XSCREEN_HEIGHT" | bc`
xinput set-prop "kamvas-pen" --type=float "Coordinate Transformation Matrix" $C>
echo Mapped tablet area to \'"$TABLET_WIDTH"x"$TABLET_HEIGHT"+"$TABLET_OFFSET_X>

**Comment by danielgrom** [comment]
woa I fixed the issue! the line XSCREEN_WIDTH is being mapped wrong in my setup, I changed to 3840  (its 1920x2) and its now working! Apparently bigger numbers dimish the area of use, the smaller it is the longer the cursor moves.

**Comment by kyledayton** [comment]
Hi @danielgrom, thanks for opening this issue. Perhaps the script should be commented a bit better. `XSCREEN_WIDTH` and `XSCREEN_HEIGHT` are the width and height respectively of the entire Xorg screen (as reported by `xrandr`) Since you have 2x 1080p monitors setup horizontally, I'm assuming that your X screen size is `3840x1920`. `TABLET_WIDTH` and `TABLET_HEIGHT` specify the resolution of graphics tablet itself (should always be `1920x1080` for the GT-220). `TABLET_OFFSET_X` and `TABLET_OFFSET_Y` are the offset of the tablet from the origin in the X screen space. For instance, If you were to place the graphics tablet as the right most monitor, you'd update `TABLET_OFFSET_X` to be `1920`.

**Comment by danielgrom** [comment]
Yes, that's the screen size. I managed to fix it by running a script at
startup with the line:
xinput --map-to-output HDMI-0
For some reason this is not being called at startup.
